### ISSUE TITLE
crewpod-observation-25

### ISSUE THREAD

**Issue by jofwu** [LouisB3/USILS-Patches#1]
You need to set "KerbalMonths=0" for crewpod-observation-25. The default is one month of "extra time", so you have to zero it out apparently. I assume this is what you intended anyways. Same goes for the pull request you have with SSPX.

**Comment by LouisB3** [comment]
Thanks, should be fixed now. 

On a tangentially related note, do you know if there are any effects of adding ModuleHabitation to parts without crew capacity? It's occurred to me that hab space would be applicable to the SSPX crew tubes and mini-cupola, but I haven't gotten around to testing it yet.

**Comment by jofwu** [comment]
Pretty sure there's no issue doing that. I actually did this myself. Gave the 4 crew tubes some KerbalMonths equal to their mass*5 and gave the mini-cupola a 0.1 multiplier (mass is 0.09, but I opted for a rounder number). Haven't sent out a ship with these parts yet, but the math in the USI-LS Window (in the Editor) checks out. Checking the SSPX parts I changed is actually how I stumbled on the original issue. :)

**Comment by LouisB3** [comment]
Okay, if it shows up in the VAB correctly then the only other thing that I think could go wrong is if ReplacementParts are not consumed correctly from non-crewable parts (I'm not familiar with the inner workings of the wear mechanic, so I have no expectations for how it might function). I'll probably want to test this at some point before making the pull request. Thanks
